version: 2.1

aliases:
  - &restore_yarn_cache
    restore_cache:
      name: Restore Node_modules Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile

jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2.1
  default:
    jobs:
      - setup
      - test:
          requires:
            - setup
