version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test

  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Build All
          command: yarn build && yarn build:components

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "$GITHUB_EMAIL"
            git config user.name "$GITHUB_USERNAME"
            git add .
            git commit -m "docs: via CircleCI build"
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/tolerance-go/keep-learning.git master

workflows:
  version: 2.1
  default:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          context: GITHUB_TOKEN
          requires:
            - build
          filters:
            branches:
              only:
                - master
