version: 2.1

aliases:
  - &restore_yarn_cache
    restore_cache:
      name: Restore Node_modules Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &run_yarn
    run:
      name: Install Packages
      command: yarn --frozen-lockfile

jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - run:
          name: Test
          command: yarn test

  build_deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - *restore_yarn_cache
      - *run_yarn
      - add_ssh_keys:
          fingerprints:
            - "46:71:0e:84:a2:5c:18:a1:a6:6f:17:a1:29:04:19:ea"
      - run:
          name: Build All
          command: yarn build && yarn build:visual && yarn build:server
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            gzip -r ./dist-server
            gzip -r ./dist-visual
            ssh $REMOTE_USERNAME@$REMOTE_IP "rm -rf $REMOTE_SERVER_PATH && mkdir -p $REMOTE_SERVER_PATH"
            ssh $REMOTE_USERNAME@$REMOTE_IP "rm -rf $REMOTE_VISUAL_PATH && mkdir -p $REMOTE_VISUAL_PATH"
            scp -r ./dist-server/* $REMOTE_USERNAME@$REMOTE_IP:$REMOTE_SERVER_PATH
            scp -r ./dist-visual/* $REMOTE_USERNAME@$REMOTE_IP:$REMOTE_VISUAL_PATH
            ssh $REMOTE_USERNAME@$REMOTE_IP "gzip -r -d $REMOTE_SERVER_PATH"
            ssh $REMOTE_USERNAME@$REMOTE_IP "gzip -r -d $REMOTE_VISUAL_PATH"
            pm2 restart $REMOTE_SERVER_PATH/service/index.js

workflows:
  version: 2.1
  default:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build_deploy:
          context: SERVER_TOKEN
          requires:
            - test
          filters:
            branches:
              only: /feat\/src-xxx\.service\.ts|master/
